swagger: "2.0"
info:
  description: "This is a sample chatbot."
  version: "1.0.0"
  title: "Chatbot"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: "/v1"
host: localhost:5000
  
schemes:
- "https"
- "http"

paths:
  /ask:
    get:
      summary: Ask a question
      produces: 
        - application/json
      parameters:
        - in: query
          name: message
          description: user sentence
          required: true
          type: string
        - in: query
          name: patient
          description: patient name
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              answer:
                type: string
              name:
                type: string
      
        
  